USE [PROYECTO_1]
GO
/****** Object:  StoredProcedure [dbo].[SP_DEL_USUARIO]    Script Date: 27/6/2024 21:13:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[SP_DEL_USUARIO]
	@PI_ID_USUARIO INTEGER,
	@PI_USUARIO_MODIFICACION INTEGER
	
AS
BEGIN
	UPDATE USUARIOS
	SET ESTADO='I',
		USUARIO_MODIFICACION=@PI_USUARIO_MODIFICACION,
		FECHA_MODIFICACION= GETDATE()
	WHERE
		ID_USUARIO=@PI_ID_USUARIO;


END
