USE [PROYECTO_1]
GO
/****** Object:  StoredProcedure [dbo].[SP_GET_USUARIO]    Script Date: 27/6/2024 21:14:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[SP_GET_USUARIO]
	@PI_ID_USUARIO INTEGER
	
AS
BEGIN
	SELECT * FROM USUARIOS WHERE ID_USUARIO=@PI_ID_USUARIO;

END
